import { createSystem } from "@chakra-ui/react"

// Define the animations as keyframes
const keyframes = {
  fadeIn: {
    "0%": { opacity: 0 },
    "100%": { opacity: 1 },
  },
  fadeOut: {
    "0%": { opacity: 1 },
    "100%": { opacity: 0, transform: "translateY(10px)" },
  },
  botMessageIn: {
    "0%": { opacity: 0, transform: "translateY(20px) scale(0.9)" },
    "100%": { opacity: 1, transform: "translateY(0) scale(1)" },
  },
  userMessageIn: {
    "0%": { opacity: 0, transform: "translateY(20px) scale(0.9)" },
    "100%": { opacity: 1, transform: "translateY(0) scale(1)" },
  },
  typingAnimation: {
    "0%, 60%, 100%": { transform: "translateY(0)", opacity: 0.6 },
    "30%": { transform: "translateY(-8px)", opacity: 1 },
  },
  headerGlow: {
    "0%": { boxShadow: "0 2px 5px rgba(0, 132, 255, 0.05)" },
    "50%": { boxShadow: "0 2px 15px rgba(0, 132, 255, 0.15)" },
    "100%": { boxShadow: "0 2px 5px rgba(0, 132, 255, 0.05)" },
  },
  bounce: {
    "0%, 20%, 50%, 80%, 100%": { transform: "translateY(0)" },
    "40%": { transform: "translateY(-8px)" },
    "60%": { transform: "translateY(-4px)" },
  },
  floating: {
    "0%": { transform: "translateY(0px)" },
    "50%": { transform: "translateY(-5px)" },
    "100%": { transform: "translateY(0px)" },
  },
  bubblePulse: {
    "0%": { transform: "scale(1)" },
    "50%": { transform: "scale(1.02)" },
    "100%": { transform: "scale(1)" },
  },
  pulseAvatar: {
    "0%": { boxShadow: "0 0 0 0 rgba(0, 132, 255, 0.4)" },
    "70%": { boxShadow: "0 0 0 5px rgba(0, 132, 255, 0)" },
    "100%": { boxShadow: "0 0 0 0 rgba(0, 132, 255, 0)" },
  },
  gradientShift: {
    "0%": { backgroundPosition: "0% 50%" },
    "50%": { backgroundPosition: "100% 50%" },
    "100%": { backgroundPosition: "0% 50%" },
  },
}

// Create a custom theme
export const theme = createSystem({
  config: {
    initialColorMode: "light",
    useSystemColorMode: false,
  },
  tokens: {
    colors: {
      primary: {
        50: "#e3f2fd",
        100: "#bbdefb",
        200: "#90caf9",
        300: "#64b5f6",
        400: "#42a5f5",
        500: "#0084ff", // Primary color from your original CSS
        600: "#0069d9", // Hover color from your original CSS
        700: "#1565c0",
        800: "#0d47a1",
        900: "#0a2351",
      },
      botMessage: {
        bg: "#0084ff",
        text: "#ffffff",
        darkBg: "#005bb5",
      },
      userMessage: {
        bg: "#e9edf1",
        text: "#333333",
        darkBg: "#3a3a3a",
      },
      timestamp: {
        light: "#8a9aa9",
        dark: "#a0a0a0",
      },
    },
  },
  keyframes,
  animation: {
    "fade-in": "fadeIn 0.3s ease-out",
    "fade-out": "fadeOut 0.3s ease-out",
    "bot-message-in": "botMessageIn 0.4s cubic-bezier(0.22, 0.61, 0.36, 1)",
    "user-message-in": "userMessageIn 0.4s cubic-bezier(0.22, 0.61, 0.36, 1)",
    "slide-in-left": "slideInLeft 0.4s cubic-bezier(0.22, 0.61, 0.36, 1)",
    "slide-in-right": "slideInRight 0.4s cubic-bezier(0.22, 0.61, 0.36, 1)",
    typing: "typingAnimation 1.5s infinite ease-in-out",
    "header-glow": "headerGlow 8s infinite alternate",
    bounce: "bounce 2s infinite",
    floating: "floating 3s ease-in-out infinite",
    "bubble-pulse": "bubblePulse 1.5s infinite",
    "pulse-avatar": "pulseAvatar 2s infinite alternate",
    "gradient-shift": "gradientShift 3s ease infinite",
  },
  styles: {
    global: (props) => ({
      body: {
        bg: props.colorMode === "dark" ? "gray.800" : "gray.50",
        color: props.colorMode === "dark" ? "white" : "gray.800",
      },
      // Add custom CSS for react-chatbot-kit
      ".react-chatbot-kit-chat-container": {
        width: "100% !important",
        maxWidth: "100% !important",
        minWidth: "100% !important",
      },
      ".react-chatbot-kit-chat-inner-container": {
        width: "100% !important",
        maxWidth: "100% !important",
        minWidth: "100% !important",
        flexGrow: "1 !important",
        overflowY: "auto !important",
        overflowX: "hidden !important",
        padding: "10px 10px 0 10px !important",
        boxSizing: "border-box !important",
        scrollBehavior: "smooth !important",
        display: "flex !important",
        flexDirection: "column !important",
        justifyContent: "flex-start !important",
        position: "relative !important",
        minHeight: "0 !important",
        maxHeight: "calc(100vh - 150px) !important",
        backgroundColor: props.colorMode === "dark" ? "gray.800" : "gray.50",
        transition: "background-color 0.3s ease !important",
        marginTop: "40px !important",
      },
      ".react-chatbot-kit-chat-header": {
        display: "none !important",
      },
      ".react-chatbot-kit-chat-message-container": {
        width: "100% !important",
        maxWidth: "100% !important",
        minWidth: "100% !important",
        padding: "0 !important",
        boxSizing: "border-box !important",
        overflowX: "hidden !important",
        position: "relative !important",
      },
      ".react-chatbot-kit-chat-bot-message": {
        maxWidth: "80% !important",
        wordWrap: "break-word !important",
        whiteSpace: "pre-wrap !important",
        padding: "12px 16px !important",
        borderRadius: "18px !important",
        margin: "5px 10px 20px 0 !important",
        fontSize: "15px !important",
        lineHeight: "1.5 !important",
        transition: "all 0.3s ease !important",
        position: "relative !important",
        boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1) !important",
        transformOrigin: "bottom left !important",
        animation: "botMessageIn 0.4s cubic-bezier(0.22, 0.61, 0.36, 1) !important",
        backgroundColor: props.colorMode === "dark" ? "#005bb5" : "#0084ff",
        color: "white !important",
        marginRight: "auto !important",
        borderBottomLeftRadius: "4px !important",
      },
      ".react-chatbot-kit-chat-user-message": {
        maxWidth: "80% !important",
        wordWrap: "break-word !important",
        whiteSpace: "pre-wrap !important",
        padding: "12px 16px !important",
        borderRadius: "18px !important",
        margin: "5px 10px 20px 0 !important",
        fontSize: "15px !important",
        lineHeight: "1.5 !important",
        transition: "all 0.3s ease !important",
        position: "relative !important",
        boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1) !important",
        transformOrigin: "bottom right !important",
        animation: "userMessageIn 0.4s cubic-bezier(0.22, 0.61, 0.36, 1) !important",
        backgroundColor: props.colorMode === "dark" ? "#3a3a3a" : "#e9edf1",
        color: props.colorMode === "dark" ? "white" : "#333333",
        marginLeft: "auto !important",
        borderBottomRightRadius: "4px !important",
      },
      ".react-chatbot-kit-chat-bot-message-arrow": {
        borderRight: props.colorMode === "dark" ? "8px solid #005bb5 !important" : "8px solid #0084ff !important",
        marginRight: "0 !important",
      },
      ".react-chatbot-kit-chat-user-message-arrow": {
        borderLeft: props.colorMode === "dark" ? "8px solid #3a3a3a !important" : "8px solid #e9edf1 !important",
      },
      ".react-chatbot-kit-chat-input-container": {
        position: "fixed !important",
        bottom: "0 !important",
        width: "100% !important",
        backgroundColor: props.colorMode === "dark" ? "#2a2a2a" : "white",
        borderTop: props.colorMode === "dark" ? "1px solid #444444" : "1px solid #e0e0e0",
        padding: "12px 15px !important",
        boxSizing: "border-box !important",
        margin: "0 !important",
        boxShadow: "0 -2px 10px rgba(0, 0, 0, 0.05) !important",
        height: "65px !important",
        zIndex: "100 !important",
        transition: "background-color 0.3s ease !important",
        left: "0 !important",
        right: "0 !important",
      },
      ".react-chatbot-kit-chat-input-form": {
        display: "flex !important",
        alignItems: "center !important",
        width: "100% !important",
        maxWidth: "100% !important",
        padding: "0 !important",
        margin: "0 !important",
      },
      ".react-chatbot-kit-chat-input": {
        flexGrow: "1 !important",
        padding: "12px 16px !important",
        borderRadius: "24px !important",
        border: props.colorMode === "dark" ? "1px solid #444444" : "1px solid #e0e0e0",
        fontSize: "15px !important",
        outline: "none !important",
        transition: "all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1) !important",
        color: props.colorMode === "dark" ? "white" : "#333333",
        backgroundColor: props.colorMode === "dark" ? "#2a2a2a" : "white",
        boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1) !important",
        margin: "0 !important",
        width: "100% !important",
      },
      ".react-chatbot-kit-chat-input:focus": {
        borderColor: "#0084ff !important",
        boxShadow: "0 0 0 3px rgba(0, 132, 255, 0.2) !important",
        transform: "translateY(-1px) !important",
      },
      ".react-chatbot-kit-chat-btn-send": {
        marginLeft: "10px !important",
        padding: "0 !important",
        background: "linear-gradient(135deg, #0084ff, #0069d9) !important",
        backgroundSize: "200% 200% !important",
        borderRadius: "50% !important",
        fontSize: "15px !important",
        color: "white !important",
        border: "none !important",
        cursor: "pointer !important",
        transition: "all 0.3s ease !important",
        width: "40px !important",
        height: "40px !important",
        display: "flex !important",
        alignItems: "center !important",
        justifyContent: "center !important",
        boxShadow: "0 4px 10px rgba(0, 0, 0, 0.2), inset 0 -2px 5px rgba(0, 0, 0, 0.1) !important",
        position: "relative !important",
        animation: "gradientShift 3s ease infinite !important",
      },
      ".react-chatbot-kit-chat-btn-send > *": {
        display: "none !important",
      },
      ".react-chatbot-kit-chat-btn-send::before": {
        display: "none !important",
      },
      ".react-chatbot-kit-chat-btn-send::after": {
        content: '""',
        width: "0",
        height: "0",
        borderLeft: "6px solid transparent",
        borderRight: "6px solid transparent",
        borderBottom: "10px solid white",
        position: "absolute",
        top: "50%",
        left: "50%",
        transform: "translate(-50%, -40%)",
        transition: "all 0.3s cubic-bezier(0.68, -0.55, 0.27, 1.55)",
      },
      ".react-chatbot-kit-chat-btn-send:hover": {
        transform: "translateY(-2px) scale(1.05) !important",
        boxShadow: "0 6px 15px rgba(0, 0, 0, 0.25), inset 0 -2px 5px rgba(0, 0, 0, 0.1) !important",
      },
      ".react-chatbot-kit-chat-btn-send:hover::after": {
        transform: "translate(-50%, -30%) !important",
        borderBottomWidth: "12px !important",
      },
      ".react-chatbot-kit-chat-btn-send:active": {
        transform: "translateY(0) scale(0.95) !important",
        boxShadow: "0 2px 5px rgba(0, 0, 0, 0.2), inset 0 -1px 3px rgba(0, 0, 0, 0.1) !important",
      },
    }),
  },
})
